apiVersion: v1
kind: ServiceAccount
metadata:
  name: cdn-cert-sync
  labels:
    app.kubernetes.io/name: cdn-cert-sync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cdn-cert-sync
  labels:
    app.kubernetes.io/name: cdn-cert-sync
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cdn-cert-sync
  labels:
    app.kubernetes.io/name: cdn-cert-sync
subjects:
  - kind: ServiceAccount
    name: cdn-cert-sync
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cdn-cert-sync
