apiVersion: v1
kind: Secret
metadata:
  name: cdn-cert-sync-aliyun
  labels:
    app.kubernetes.io/name: cdn-cert-sync
type: Opaque
stringData:
  accessKeyId: <aliyun-access-key-id>
  accessKeySecret: <aliyun-access-key-secret>
